name: AI Bot Continuous

on:
  schedule:
    - cron: "0 7-23 * * *"
    - cron: "0 0-1 * * *"
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 58

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run single check
        env:
          COOKIES_JSON: ${{ secrets.COOKIES_JSON }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NINJAS_API_KEY: ${{ secrets.NINJAS_API_KEY }}
        run: python main.py
